package Presentacion;


import SistemaControlGastos.Negocio.IconsultaGastos;
import SistemaControlGastos.Negocio.consultaGastos;
import SistemaControlGastos.Negocio.gastosDTO;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;

import javax.swing.JOptionPane;

/**
 *
 * 
 */
public class DlgAgregar extends javax.swing.JDialog {

    long idUsuario;
    IconsultaGastos Consulta;
    int vecesC=0;

    /**
     * Creates new form DlgRegistro
     *
     * @param parent
     * @param modal
     */
    public DlgAgregar(java.awt.Frame parent, boolean modal) {
        super(parent, modal);

        initComponents();

    }

    public DlgAgregar() {
        initComponents();
      
        Consulta = new consultaGastos();
        ingresarSoloNumeros();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        campoDesc = new javax.swing.JTextField();
        campoMon = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        BotonRegistro1 = new javax.swing.JButton();
        date = new com.toedter.calendar.JDateChooser();
        BotonLimpiar = new javax.swing.JButton();
        BotonRegreso1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        campoCat = new javax.swing.JComboBox<>();
        lblTituloSeccion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agregar");

        jPanel1.setBackground(new java.awt.Color(235, 250, 239));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(71, 100, 104));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
        jLabel1.setText("Categoria:");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, -1, 24));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
        jLabel2.setText("Descripcion:");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, -1, 24));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
        jLabel3.setText("Monto:");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, -1, 24));

        campoDesc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoDescKeyTyped(evt);
            }
        });
        jPanel2.add(campoDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 219, -1));

        campoMon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoMonActionPerformed(evt);
            }
        });
        campoMon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoMonKeyTyped(evt);
            }
        });
        jPanel2.add(campoMon, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 219, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        jLabel6.setText("Fecha :");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, -1, -1));

        BotonRegistro1.setBackground(new java.awt.Color(0, 204, 153));
        BotonRegistro1.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
        BotonRegistro1.setText("Agregar");
        BotonRegistro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRegistro1ActionPerformed(evt);
            }
        });
        jPanel2.add(BotonRegistro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 350, -1, 42));
        jPanel2.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 130, -1));

        BotonLimpiar.setBackground(new java.awt.Color(0, 204, 153));
        BotonLimpiar.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
        BotonLimpiar.setText("Limpiar");
        BotonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonLimpiarActionPerformed(evt);
            }
        });
        jPanel2.add(BotonLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 370, 110, 30));

        BotonRegreso1.setBackground(new java.awt.Color(0, 204, 153));
        BotonRegreso1.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
        BotonRegreso1.setText("Volver");
        BotonRegreso1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRegreso1ActionPerformed(evt);
            }
        });
        jPanel2.add(BotonRegreso1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 30));

        campoCat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alimentacion", "Transporte", "Ocio" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(campoCat, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(campoCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(197, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 300, 260));

        lblTituloSeccion.setFont(new java.awt.Font("Segoe UI Black", 2, 48)); // NOI18N
        lblTituloSeccion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloSeccion.setText("Agregar Gasto");
        jPanel2.add(lblTituloSeccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, -10, 350, 70));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 420));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BotonRegistro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRegistro1ActionPerformed
        // Verifica si los campos están vacíos
        int seleccion=campoCat.getSelectedIndex();
        if (seleccion==-1 || campoDesc.getText().isEmpty() ||campoMon.getText().isEmpty()|| date.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos", "Alerta", JOptionPane.WARNING_MESSAGE);
        } else {
            
       float mon= Float.parseFloat(campoMon.getText());
            switch (seleccion) {
                
            case 0:
                System.out.println(idUsuario);
                       

                  gastosDTO  Agregar=new gastosDTO("Alimentacion", campoDesc.getText(), mon, date.getDate(),idUsuario);
                    Consulta.registrar(Agregar);

                    JOptionPane.showMessageDialog(this, "gasto agregada con éxito", "Confirmación", JOptionPane.INFORMATION_MESSAGE);
                    //dlg.idUsuarioRecibido=idUsuario;
                    DlgConsultas dlg=new DlgConsultas(idUsuario);
                    dlg.setVisible(true);
                    
                    dispose();
                break;
           
                case 1:

                  gastosDTO  Agregar1=new gastosDTO("Transporte", campoDesc.getText(),mon, date.getDate(),idUsuario);
                    Consulta.registrar(Agregar1);

                    JOptionPane.showMessageDialog(this, "gasto agregada con éxito", "Confirmación", JOptionPane.INFORMATION_MESSAGE);
                   // dlg.idUsuarioRecibido=idUsuario;
                    DlgConsultas dlg2=new DlgConsultas(idUsuario);
                    dlg2.setVisible(true);
                    dispose();
 
                break;
                 case 2:
                  gastosDTO  Agregar2=new gastosDTO("Ocio", campoDesc.getText(),mon, date.getDate(),idUsuario);
                    Consulta.registrar(Agregar2);
                    JOptionPane.showMessageDialog(this, "gasto agregada con éxito", "Confirmación", JOptionPane.INFORMATION_MESSAGE);
                    //dlg.idUsuarioRecibido=idUsuario;
                    DlgConsultas dlg3=new DlgConsultas(idUsuario);
                    dlg3.setVisible(true);
                    
                    dispose();
 
                break;   
            default:
                JOptionPane.showMessageDialog(this, "Gasto no valido", "Error", JOptionPane.ERROR_MESSAGE);
                return;
        }
      }                        
    }//GEN-LAST:event_BotonRegistro1ActionPerformed
private void ingresarSoloNumeros(){
        campoMon.addKeyListener(new KeyAdapter() {
            @Override
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();
                if (!Character.isDigit(c) && c != KeyEvent.VK_BACK_SPACE) {
                    e.consume();
                }
            }
        });
}
    private void BotonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonLimpiarActionPerformed
        // TODO add your handling code here:
        campoDesc.setText(" ");
        campoMon.setText(" ");
      
        date.setDate(null);
       
    }//GEN-LAST:event_BotonLimpiarActionPerformed
   
    private void BotonRegreso1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRegreso1ActionPerformed
        // TODO add your handling code here:
        DlgConsultas dlg=new DlgConsultas(idUsuario);
        dlg.idUsuarioRecibido=idUsuario;
        dlg.setVisible(true);
        dispose();
    }//GEN-LAST:event_BotonRegreso1ActionPerformed

    private void campoDescKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoDescKeyTyped
        // TODO add your handling code here:
       
    }//GEN-LAST:event_campoDescKeyTyped

    private void campoMonKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoMonKeyTyped
        
       
    }//GEN-LAST:event_campoMonKeyTyped

    private void campoMonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoMonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoMonActionPerformed

   

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(DlgRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(DlgRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(DlgRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(DlgRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                DlgRegistro dialog = new DlgRegistro(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonLimpiar;
    private javax.swing.JButton BotonRegistro1;
    private javax.swing.JButton BotonRegreso1;
    private javax.swing.JComboBox<String> campoCat;
    private javax.swing.JTextField campoDesc;
    private javax.swing.JTextField campoMon;
    private com.toedter.calendar.JDateChooser date;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblTituloSeccion;
    // End of variables declaration//GEN-END:variables
}
