package Presentacion;


import Negocio.dtos.IconsultaGastos;
import Negocio.dtos.consultaGastos;
import Negocio.dtos.gastosDTO;

import javax.swing.JOptionPane;

/**
 *
 * @author molin
 */
public class DlgAgregar extends javax.swing.JDialog {

    
    IconsultaGastos Consulta;
    int vecesC=0;

    /**
     * Creates new form DlgRegistro
     *
     * @param parent
     * @param modal
     */
    public DlgAgregar(java.awt.Frame parent, boolean modal) {
        super(parent, modal);

        initComponents();

    }

    public DlgAgregar() {
        initComponents();
      
        Consulta = new consultaGastos();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        campoCat = new javax.swing.JTextField();
        campoDesc = new javax.swing.JTextField();
        campoMon = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        BotonRegistro1 = new javax.swing.JButton();
        date = new com.toedter.calendar.JDateChooser();
        BotonLimpiar = new javax.swing.JButton();
        BotonRegreso1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("REGISTRO");

        jPanel1.setBackground(new java.awt.Color(235, 250, 239));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Categoria:");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, -1, 24));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Descripcion:");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, -1, 24));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Monto:");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, -1, 24));

        campoCat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoCatKeyTyped(evt);
            }
        });
        jPanel2.add(campoCat, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 219, -1));

        campoDesc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoDescKeyTyped(evt);
            }
        });
        jPanel2.add(campoDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 219, -1));

        campoMon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoMonActionPerformed(evt);
            }
        });
        campoMon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoMonKeyTyped(evt);
            }
        });
        jPanel2.add(campoMon, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 219, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Fecha :");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, -1, -1));

        BotonRegistro1.setBackground(new java.awt.Color(51, 153, 0));
        BotonRegistro1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        BotonRegistro1.setForeground(new java.awt.Color(255, 255, 255));
        BotonRegistro1.setText("Agregar");
        BotonRegistro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRegistro1ActionPerformed(evt);
            }
        });
        jPanel2.add(BotonRegistro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, -1, 42));
        jPanel2.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 130, -1));

        BotonLimpiar.setBackground(new java.awt.Color(153, 255, 102));
        BotonLimpiar.setFont(new java.awt.Font("Segoe UI Black", 1, 8)); // NOI18N
        BotonLimpiar.setText("Limpiar");
        BotonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonLimpiarActionPerformed(evt);
            }
        });
        jPanel2.add(BotonLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 70, 30));

        BotonRegreso1.setBackground(new java.awt.Color(153, 255, 102));
        BotonRegreso1.setFont(new java.awt.Font("Segoe UI Black", 1, 8)); // NOI18N
        BotonRegreso1.setText("Volver");
        BotonRegreso1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRegreso1ActionPerformed(evt);
            }
        });
        jPanel2.add(BotonRegreso1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 620, 410));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 698, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BotonRegistro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRegistro1ActionPerformed
        // Verifica si los campos están vacíos
        if (campoCat.getText().isEmpty() || campoDesc.getText().isEmpty() ||campoMon.getText().isEmpty()|| date.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos", "Alerta", JOptionPane.WARNING_MESSAGE);
        } else {
           float mon= Float.parseFloat(campoMon.getText());
                  gastosDTO  Agregar=new gastosDTO(campoCat.getText(), campoDesc.getText(), mon, date.getDate());
                    Consulta.registrar(Agregar);

                    JOptionPane.showMessageDialog(this, "gasto agregada con éxito", "Confirmación", JOptionPane.INFORMATION_MESSAGE);
                    DlgConsultas dlg=new DlgConsultas();
                    dlg.setVisible(true);
                    
                    dispose();
                
            }
        
    }//GEN-LAST:event_BotonRegistro1ActionPerformed

    private void BotonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonLimpiarActionPerformed
        // TODO add your handling code here:
        campoCat.setText(" ");
        campoDesc.setText(" ");
        campoMon.setText(" ");
      
        date.setDate(null);
       
    }//GEN-LAST:event_BotonLimpiarActionPerformed
   
    private void BotonRegreso1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRegreso1ActionPerformed
        // TODO add your handling code here:
        DlgConsultas dlg=new DlgConsultas();
        dlg.setVisible(true);
        dispose();
    }//GEN-LAST:event_BotonRegreso1ActionPerformed

    private void campoDescKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoDescKeyTyped
        // TODO add your handling code here:
       
    }//GEN-LAST:event_campoDescKeyTyped

    private void campoMonKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoMonKeyTyped
        // TODO add your handling code here:
       
    }//GEN-LAST:event_campoMonKeyTyped

    private void campoCatKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoCatKeyTyped
       
    }//GEN-LAST:event_campoCatKeyTyped

    private void campoMonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoMonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoMonActionPerformed

   

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(DlgRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(DlgRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(DlgRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(DlgRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                DlgRegistro dialog = new DlgRegistro(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonLimpiar;
    private javax.swing.JButton BotonRegistro1;
    private javax.swing.JButton BotonRegreso1;
    private javax.swing.JTextField campoCat;
    private javax.swing.JTextField campoDesc;
    private javax.swing.JTextField campoMon;
    private com.toedter.calendar.JDateChooser date;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
