package Presentacion;

//import Control.ControlPresentacion;
import Negocio.dtos.IconsultaGastos;
import Negocio.dtos.consultaGastos;
import Negocio.dtos.gastosDTO;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class DlgConsultas extends javax.swing.JFrame {

    
    List<gastosDTO> gastos;
    IconsultaGastos p;
    private DefaultTableModel modeloTabla;

    /**
     * Creates new form FrmOpcionesCliente
     */
    public DlgConsultas() {
        p=new consultaGastos();
        initComponents();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelOpciones = new javax.swing.JPanel();
        lblTituloSeccion = new javax.swing.JLabel();
        cbxBusqueda = new javax.swing.JComboBox<>();
        txtCoincidencia = new javax.swing.JTextField();
        lblOpciones = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnSeleccionar = new javax.swing.JButton();
        lblOpciones1 = new javax.swing.JLabel();
        lblOpciones2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabla = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        lblOpciones3 = new javax.swing.JLabel();
        dateChooserInicio = new com.toedter.calendar.JDateChooser();
        dateChooserFin = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelOpciones.setBackground(new java.awt.Color(204, 255, 204));
        panelOpciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTituloSeccion.setFont(new java.awt.Font("Amazon Ember", 1, 48)); // NOI18N
        lblTituloSeccion.setForeground(new java.awt.Color(64, 53, 44));
        lblTituloSeccion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloSeccion.setText("Consultas");
        panelOpciones.add(lblTituloSeccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 750, -1));

        cbxBusqueda.setBackground(new java.awt.Color(132, 203, 132));
        cbxBusqueda.setFont(new java.awt.Font("Amazon Ember Light", 0, 18)); // NOI18N
        cbxBusqueda.setForeground(new java.awt.Color(51, 51, 51));
        cbxBusqueda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "categoria", "monto" }));
        cbxBusqueda.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(64, 53, 44), 2));
        cbxBusqueda.setFocusable(false);
        cbxBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxBusquedaActionPerformed(evt);
            }
        });
        panelOpciones.add(cbxBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 230, 40));

        txtCoincidencia.setBackground(new java.awt.Color(132, 203, 132));
        txtCoincidencia.setFont(new java.awt.Font("Amazon Ember Light", 0, 20)); // NOI18N
        txtCoincidencia.setForeground(new java.awt.Color(51, 51, 51));
        txtCoincidencia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(64, 53, 44), 2));
        txtCoincidencia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCoincidenciaKeyPressed(evt);
            }
        });
        panelOpciones.add(txtCoincidencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 260, 40));

        lblOpciones.setFont(new java.awt.Font("Amazon Ember", 0, 24)); // NOI18N
        lblOpciones.setForeground(new java.awt.Color(64, 53, 44));
        lblOpciones.setText("Periodo:");
        panelOpciones.add(lblOpciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 80, -1, -1));

        btnCancelar.setBackground(new java.awt.Color(0, 153, 0));
        btnCancelar.setFont(new java.awt.Font("Amazon Ember", 0, 24)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorderPainted(false);
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.setFocusable(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        panelOpciones.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 160, 50));

        btnSeleccionar.setBackground(new java.awt.Color(0, 153, 0));
        btnSeleccionar.setFont(new java.awt.Font("Amazon Ember", 0, 24)); // NOI18N
        btnSeleccionar.setForeground(new java.awt.Color(255, 255, 255));
        btnSeleccionar.setText("Filtrar fecha");
        btnSeleccionar.setBorderPainted(false);
        btnSeleccionar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSeleccionar.setFocusable(false);
        btnSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarActionPerformed(evt);
            }
        });
        panelOpciones.add(btnSeleccionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 370, 160, 50));

        lblOpciones1.setFont(new java.awt.Font("Amazon Ember", 0, 36)); // NOI18N
        lblOpciones1.setForeground(new java.awt.Color(64, 53, 44));
        lblOpciones1.setText("Opciones");
        panelOpciones.add(lblOpciones1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, -1, -1));

        lblOpciones2.setFont(new java.awt.Font("Amazon Ember", 0, 24)); // NOI18N
        lblOpciones2.setForeground(new java.awt.Color(64, 53, 44));
        lblOpciones2.setText("Busqueda por:");
        panelOpciones.add(lblOpciones2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        jTabla.setBackground(new java.awt.Color(132, 203, 132));
        jTabla.setFont(new java.awt.Font("Amazon Ember", 0, 12)); // NOI18N
        jTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Categoria", "Descripcion", "Monto", "Fecha"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTabla);

        panelOpciones.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 670, 100));

        jButton1.setText("AgregarNuevo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panelOpciones.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, -1, -1));

        jButton2.setText("Modificar");
        panelOpciones.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 390, -1, -1));

        jButton3.setText("Eliminar");
        panelOpciones.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 390, -1, -1));

        lblOpciones3.setFont(new java.awt.Font("Amazon Ember", 0, 24)); // NOI18N
        lblOpciones3.setForeground(new java.awt.Color(64, 53, 44));
        lblOpciones3.setText("Coincidencia:");
        panelOpciones.add(lblOpciones3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, -1, -1));
        panelOpciones.add(dateChooserInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 130, -1, -1));
        panelOpciones.add(dateChooserFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 130, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Hasta:");
        panelOpciones.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 110, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Desde:");
        panelOpciones.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 110, -1, -1));

        getContentPane().add(panelOpciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxBusquedaActionPerformed
       
    }//GEN-LAST:event_cbxBusquedaActionPerformed

    private void btnSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarActionPerformed
//        int filaSeleccionada = jTabla.getSelectedRow();
//
//        if ( filaSeleccionada != -1) { // Verificar si se ha seleccionado alguna fila
//            Object[] datosFila = new Object[jTabla.getColumnCount()];
//
//            for (int i = 0; i < jTabla.getColumnCount(); i++) {
//                datosFila[i] = jTabla.getValueAt(filaSeleccionada, i);
//            }
//            String rfc=datosFila[1].toString();
//             control.desplegarDlgHistorial(rfc);
//            this.dispose();
            
        //}
       
    }//GEN-LAST:event_btnSeleccionarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
         //control.desplegarMenu();
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtCoincidenciaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCoincidenciaKeyPressed
        buscarCoincidencias(txtCoincidencia.getText() + evt.getKeyChar());
    }//GEN-LAST:event_txtCoincidenciaKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
    private void buscarCoincidencias(String texto) {
        limpiarTabla();
        int sele = cbxBusqueda.getSelectedIndex();
        gastos=p.obtenerListaPersonas();
         // Obtener las fechas del periodo desde los campos de entrada
    Date fechaInicio = dateChooserInicio.getDate();
    Date fechaFin = dateChooserFin.getDate();
    
        switch (sele) {
            case 0:
                for (gastosDTO pn : gastos) {
                    if (pn.getCurp().contains(texto)) {
                        insertarFila(pn);
                                

                    }
                }
                break;
            case 1:
                // Buscar por fecha en un rango
            if (fechaInicio != null && fechaFin != null) {
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                for (PersonasDTO pn : personas) {
                    // Formatear fecha de nacimiento
                    String fechaFormateada = sdf.format(pn.getFechaNacimiento());
                    
                    // Convertir fecha de nacimiento a objeto Date para la comparación
                    try {
                        Date fechaNacimiento = sdf.parse(fechaFormateada);
                        if (fechaNacimiento.compareTo(fechaInicio) >= 0 && fechaNacimiento.compareTo(fechaFin) <= 0) {
                            insertarFila(pn);
                        }
                    } catch (ParseException e) {
                        e.printStackTrace();
                    }
                }
            } else {
                JOptionPane.showMessageDialog(this, "Por favor, ingrese el rango de fechas", "Advertencia", JOptionPane.WARNING_MESSAGE);
            }
            break;                
                case 2:
                    for (gastosDTO pn : gastos) {
                    if (pn.getNombre().contains(texto)) {
                        insertarFila(pn);
                    }
                }
                break;
                    
            default:
                JOptionPane.showMessageDialog(this, "Busqueda no valida", "Error", JOptionPane.ERROR_MESSAGE);
                return;
        }
        

        }

    

    private void limpiarTabla() {
        modeloTabla = (DefaultTableModel) jTabla.getModel();
        if (modeloTabla.getRowCount() > 0) {
            for (int i = modeloTabla.getRowCount() - 1; i > -1; i--) {
                modeloTabla.removeRow(i);
            }
        }
    }

    private void insertarFila(gastosDTO p) {
        Object[] fila = {
            p.getNombre(),
            p.getRFC(),
            p.getApellidoP(),
            p.getApellidoM(),
            p.getFecha(),
            p.getCurp(),
            p.getTelefono()
            
            };
        modeloTabla.addRow(fila);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSeleccionar;
    private javax.swing.JComboBox<String> cbxBusqueda;
    private com.toedter.calendar.JDateChooser dateChooserFin;
    private com.toedter.calendar.JDateChooser dateChooserInicio;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTabla;
    private javax.swing.JLabel lblOpciones;
    private javax.swing.JLabel lblOpciones1;
    private javax.swing.JLabel lblOpciones2;
    private javax.swing.JLabel lblOpciones3;
    private javax.swing.JLabel lblTituloSeccion;
    private javax.swing.JPanel panelOpciones;
    private javax.swing.JTextField txtCoincidencia;
    // End of variables declaration//GEN-END:variables

}
