package Presentacion;


import Negocio.dtos.IconsultaGastos;
import Negocio.dtos.consultaGastos;

import java.text.ParseException;
import java.text.SimpleDateFormat;

import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author molin
 */
public class DlgModificar extends javax.swing.JDialog {

    IconsultaGastos Consulta;
    int vecesC=0;
    String idCambio;
    String catCambio;
    String desCambio;
    String montCambio;
    String fechaCambio;

    /**
     * Creates new form DlgRegistro
     *
     * @param parent
     * @param modal
     */
    public DlgModificar(java.awt.Frame parent, boolean modal) {
        super(parent, modal);

        initComponents();

    }

    public DlgModificar() {
        initComponents();
        Consulta = new consultaGastos();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        campoCat = new javax.swing.JTextField();
        campoDes = new javax.swing.JTextField();
        campoMont = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        BotonRegistro1 = new javax.swing.JButton();
        date = new com.toedter.calendar.JDateChooser();
        BotonLimpiar = new javax.swing.JButton();
        BotonRegreso1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("REGISTRO");

        jPanel1.setBackground(new java.awt.Color(235, 250, 239));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Categoria:");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, -1, 24));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Descripcion:");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, -1, 24));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Monto:");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, -1, 24));

        campoCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCatActionPerformed(evt);
            }
        });
        campoCat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoCatKeyTyped(evt);
            }
        });
        jPanel2.add(campoCat, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 219, -1));

        campoDes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoDesActionPerformed(evt);
            }
        });
        campoDes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoDesKeyTyped(evt);
            }
        });
        jPanel2.add(campoDes, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 219, -1));

        campoMont.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoMontKeyTyped(evt);
            }
        });
        jPanel2.add(campoMont, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 219, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Fecha:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, -1, -1));

        BotonRegistro1.setBackground(new java.awt.Color(51, 153, 0));
        BotonRegistro1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        BotonRegistro1.setForeground(new java.awt.Color(255, 255, 255));
        BotonRegistro1.setText("Guardar ");
        BotonRegistro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRegistro1ActionPerformed(evt);
            }
        });
        jPanel2.add(BotonRegistro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, -1, 42));
        jPanel2.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 130, -1));

        BotonLimpiar.setBackground(new java.awt.Color(153, 255, 102));
        BotonLimpiar.setFont(new java.awt.Font("Segoe UI Black", 1, 8)); // NOI18N
        BotonLimpiar.setText("Limpiar");
        BotonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonLimpiarActionPerformed(evt);
            }
        });
        jPanel2.add(BotonLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 370, 70, 30));

        BotonRegreso1.setBackground(new java.awt.Color(153, 255, 102));
        BotonRegreso1.setFont(new java.awt.Font("Segoe UI Black", 1, 8)); // NOI18N
        BotonRegreso1.setText("Volver");
        BotonRegreso1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRegreso1ActionPerformed(evt);
            }
        });
        jPanel2.add(BotonRegreso1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 620, 410));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 698, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BotonRegistro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRegistro1ActionPerformed
        // Verifica si los campos están vacíos
        if ( campoCat.getText().isEmpty() ){
            campoCat.setText(catCambio);
             if(campoDes.getText().isEmpty()){
                 campoDes.setText(desCambio);
             }
             if(campoMont.getText().isEmpty()){
                 
                 campoMont.setText(montCambio);
             }
             if(date.getDate()==null){
                 SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
             try {
                 // Convertir la cadena a tipo Date
                 Date fecha = sdf.parse(fechaCambio);
                 date.setDate(fecha);
             } catch (ParseException e) {
            System.out.println("Error: La cadena no tiene el formato de fecha valido.");
            e.printStackTrace();            
             }
                 
             }
        } else {
           
        }
         long num= Long.parseLong(idCambio);
         float mont=Float.valueOf(montCambio);
         Consulta.actualizarGastos(num, campoCat.getText(), campoDes.getText(), mont, date.getDate());
          DlgConsultas dlg=new DlgConsultas();
                    dlg.setVisible(true);
                    
                    dispose();    
    }//GEN-LAST:event_BotonRegistro1ActionPerformed

    private void BotonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonLimpiarActionPerformed
        // TODO add your handling code here:
        
        campoCat.setText(" ");
        campoDes.setText(" ");
        campoMont.setText(" ");
        date.setDate(null);
        
    }//GEN-LAST:event_BotonLimpiarActionPerformed
   
    
    private void BotonRegreso1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRegreso1ActionPerformed
        // TODO add your handling code here:
        DlgConsultas dlg=new DlgConsultas();
        dlg.setVisible(true);
        dispose();
    }//GEN-LAST:event_BotonRegreso1ActionPerformed

    private void campoCatKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoCatKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_campoCatKeyTyped

    private void campoDesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoDesKeyTyped
        // TODO add your handling code here:
      
    }//GEN-LAST:event_campoDesKeyTyped

    private void campoMontKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoMontKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_campoMontKeyTyped

    private void campoDesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoDesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoDesActionPerformed

    private void campoCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCatActionPerformed

    

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(DlgRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(DlgRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(DlgRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(DlgRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                DlgRegistro dialog = new DlgRegistro(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonLimpiar;
    private javax.swing.JButton BotonRegistro1;
    private javax.swing.JButton BotonRegreso1;
    private javax.swing.JTextField campoCat;
    private javax.swing.JTextField campoDes;
    private javax.swing.JTextField campoMont;
    private com.toedter.calendar.JDateChooser date;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
