/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

import SistemaUsuario.Negocio.ConsultaUsuario;
import SistemaUsuario.Negocio.IConsultaUsuario;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author dell
 */
public class Login extends javax.swing.JFrame {

    IConsultaUsuario Consulta;

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        Consulta = new ConsultaUsuario();
        this.setResizable(false); // Evita que la ventana se pueda redimensionar
        this.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
        //this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NombreUsuario = new javax.swing.JTextField();
        Contraseña = new javax.swing.JPasswordField();
        Registrar = new javax.swing.JLabel();
        Login_Foto = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NombreUsuario.setBackground(new java.awt.Color(71, 100, 104));
        NombreUsuario.setFont(new java.awt.Font("Segoe UI Black", 2, 24)); // NOI18N
        NombreUsuario.setBorder(null);
        NombreUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreUsuarioActionPerformed(evt);
            }
        });
        NombreUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NombreUsuarioKeyTyped(evt);
            }
        });
        getContentPane().add(NombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 220, 30));

        Contraseña.setBackground(new java.awt.Color(71, 100, 104));
        Contraseña.setFont(new java.awt.Font("Segoe UI Black", 3, 24)); // NOI18N
        Contraseña.setBorder(null);
        Contraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContraseñaActionPerformed(evt);
            }
        });
        getContentPane().add(Contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 210, 30));

        Registrar.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        Registrar.setForeground(new java.awt.Color(255, 255, 255));
        Registrar.setText("¿No tienes Cuenta? Registrate aquí");
        getContentPane().add(Registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, 230, -1));

        Login_Foto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/login.jpg"))); // NOI18N
        getContentPane().add(Login_Foto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btnLogin.setBorder(null);
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, 280, 40));

        btnNuevo.setText("jButton1");
        btnNuevo.setActionCommand("registrar");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        getContentPane().add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, 90, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void NombreUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreUsuarioActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_NombreUsuarioActionPerformed

    private void ContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContraseñaActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        UsuarioNuevo dl = new UsuarioNuevo();
        dl.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:

        if (NombreUsuario.getText().isEmpty() || Contraseña.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos", "Alerta", JOptionPane.WARNING_MESSAGE);
        } else {
            long id = Consulta.obtenerIDusuario(NombreUsuario.getText(), Contraseña.getText());
            if (id != 0) {
                System.out.println("mandando usuario");
                DlgConsultas v = new DlgConsultas(id);
                System.out.println(id);
                // v.idUsuarioRecibido=id;
                //JOptionPane.showMessageDialog(this, "Usuario registrado con éxito,regrese para iniciar sesion", "", JOptionPane.INFORMATION_MESSAGE);

                v.setVisible(true);
                dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Este usuario No existe", "aviso", JOptionPane.INFORMATION_MESSAGE);
                NombreUsuario.setText("");
                Contraseña.setText("");
            }
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void NombreUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NombreUsuarioKeyTyped
        // TODO // Obtiene el carácter que se ha escrito
        char c = evt.getKeyChar();

        // Permitir solo letras, números y espacios
        if (!Character.isLetterOrDigit(c) && !Character.isWhitespace(c) && c != '\b') {
            evt.consume();
            JOptionPane.showMessageDialog(this, "Solo se permiten letras, números y espacios", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_NombreUsuarioKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField Contraseña;
    private javax.swing.JLabel Login_Foto;
    private javax.swing.JTextField NombreUsuario;
    private javax.swing.JLabel Registrar;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnNuevo;
    // End of variables declaration//GEN-END:variables
}
